### ISSUE TITLE
Gas Filters Turning Off

### ISSUE THREAD

**Issue by Ledwin1233** [OracleStation/OracleStation#1004]
Round ID: 3052

I've noticed for a while everytime I play station engineer after I set the cooling loop up on MetaStation and leave to fill up the plasma tanks, I come back to every gas filter turned off. I know for sure I turned these on for I see the pressure is still set to max. This seems to only happen once per round but it always happens during round start when the engine is getting set up for the first time.

**Comment by coldud13** [comment]
it happens if you turn off the engineering APC, which i’m guessing occurs when you go to fill up the plasma tanks by turning it off and prying open the blast doors
