### ISSUE TITLE
Weapon rechargers no longer accepting weapons

### ISSUE THREAD

**Issue by dapnee** [OracleStation/OracleStation#1009]
At least starting today, you can no longer place rechargeable weapons into rechargers. When attempting to do so, you begin to attack the charger instead.

**Comment by AffectedArc07** [comment]
Were you on harm intent?

**Comment by dapnee** [comment]
Everyone is having this issue, and I've tried it on multiple intents. No I was not.

**Comment by Affurit** [comment]
Testing this on an up to date server, can't replicate. I'd test it on the actual server but uh... >.>

**Comment by Quantum-M** [comment]
This issue pops up sometimes, I seen some rounds where weapons recharge normally, others were the issue mentioned happens, round ID: 3135 is a example.

**Comment by AndrewMontagne** [comment]
Could never reproduce this. Reports of it have dried up.
