### ISSUE TITLE
Simple mobs and SNPCs chug Estus in combat and are IMMORTAL/Simplemobs cannot be killed with melee

### ISSUE THREAD

**Issue by EldritchSigma** [OracleStation/OracleStation#101]
So uh this is an issue we encountered yesterday on multiple instances: Portal storm happened and spawned combine I mean Syndie Troopers. Which didnt want to die despite armblading them for a good 5 minutes and emptying 2 Energy Guns into them (the one without the E-Shield that is). Next round spiders happened, some died in melee other straigth up refused (Medbay spider had 5 people beating on it without it dying). Then last but not least a Goliath on Lavaland refused to take ANY damage whatsoever when prodding him for a good 5 minutes with two handed spears as Ashwalkers. Not sure if this is intended but considering spiders have the issue I doubt it is. Fucking Combat Chuggers. Either have to use a casul dex build or a scrub mage build to beat them.

**Comment by Birdtalon** [comment]
I think this is related to #96

**Comment by EldritchSigma** [comment]
Looks like it. I remember Bianka complaining about unkillable animals earlier.
