### ISSUE TITLE
Gun Rechargers/All-in-one Grinders Bug

### ISSUE THREAD

**Issue by Tatsu500** [OracleStation/OracleStation#1019]
Issue reported from Round ID: 3176 (Oracle Station | Medium RP)

I was going to make some food that required flour and when i tried to put the wheat on the grinder it did not work it said "You cannot refine it into a reagent" or something similar, i heard the gun rechargers have the same issue where you can't recharger your gun.

**Comment by SamHPurp** [comment]
I've tried a few times, I cannot re-produce. What version of 512 are you using?

**Comment by miniusAreas** [comment]
@AndrewMontagne Can reproduce, using latest byond, 1 sheet of plasma wont get refined into a retegent.
Had this happen and have gotten a ahelp or two about it.
