### ISSUE TITLE
Xenobio Mutation toxins are borked

### ISSUE THREAD

**Issue by Ismothers** [OracleStation/OracleStation#1026]
Xenobiology mutation toxins are broken. They make you collapse like normal, but there isn't any changing effect. This started once andrew pushed his 'all mutation toxins need 1u' commit

**Comment by AndrewMontagne** [comment]
When did you last encounter this? We recently merged a fix for this.

**Comment by SamHPurp** [comment]
I can't reproduce, is this now fixed by #1021 ?

**Comment by AndrewMontagne** [comment]
If this comes up again we can look into it.
