### ISSUE TITLE
EMP-Kit contains 5 EMP grenades, slight balance issue.

### ISSUE THREAD

**Issue by EldritchSigma** [OracleStation/OracleStation#103]
Simple one. On the hijack and kill 2 guys shift I had last night I bought carp and an EMP Kit. The implanter was in along with 5(!) emp grenades. Considering the price is 2 TC only the ammount of grenades should be lowered to 1 or maybe 2. 5 is pretty much overkill if you ask me. The implanter alone is worth 2 TC...

**Comment by SamHPurp** [comment]
I agree with you. I'd support it dropping to 2.

**Comment by SamHPurp** [comment]
I've had a re-think. When we have IPCs I'd support this. I think for the moment maybe its fine?

Disagree?

**Comment by Birdtalon** [comment]
I still think 5 is a lot for 2 TC. You can create an awful lot of problems with EMPs

**Comment by EldritchSigma** [comment]
Hm we dont have IPCs, still EMPs can shock so many doors, drain APCs, disable cameras and also break implants on TG-Codebase. Maybe not reducing them to 2, maybe to 3 or something. But yeah we dont have any species with EMP weakness yet.

**Comment by ktoma36** [comment]
Didnt vox just get merged? I thought they had EMP weakness

**Comment by SamHPurp** [comment]
@ktoma36 got not vox yet

**Comment by Ralta** [comment]
Buy 10 boxes. Throw 50 EMP grenades. Win everything.

**Comment by SamHPurp** [comment]
Balance concern, not for the issues. Feel free to PR the change though.
