### ISSUE TITLE
If an admin aghosts and offers their body to the ghosts the player panel breaks

### ISSUE THREAD

**Issue by Cactus2388** [OracleStation/OracleStation#1043]
An admin makes an event character 

they aghost out of it

they offer it to the ghosts

a ghost takes it

the admin who aghosted uses the player panel to spawn himself as a human

it spawns the person who was inside the ghost role as that admins character, deleting whatever they had on and making them an entirely new character.

**Comment by FlattestGuitar** [comment]
A classic one, going back like ten years. I've tried to fix it in the past, but the whole system is spaghetti.

**Comment by Ralta** [comment]
Yeah I noticed this awhile back, but was told it's all but unfixable.

For what it's worth, @Cactus2388 you can spawn a new human body using the game panel (spawn a fresh human, DO NOT humanise yourself) and put yourself inside it. That will fix it.
