### ISSUE TITLE
"Fabulous" AI core sprite shows the default AI core for a while. 

### ISSUE THREAD

**Issue by oversane** [OracleStation/OracleStation#1081]
been a while since i played as AI but this issue MIGHT still exist

also replicating this is easy
1. play as AI
2. set your core display to fabulous
3. dont blink(or do, it seems like this shows up for more than a second)

**Comment by Ziiro** [comment]
![mspaint_2018-07-20_12-36-39](https://user-images.githubusercontent.com/26494679/43019254-936e109a-8c19-11e8-9ddf-fac2700a141f.png)

Not an issue, it's part of the animation.

**Comment by oversane** [comment]
oh thats weird to have it part of the animation but ok

closing the issue then

**Comment by Ziiro** [comment]
When I was originally porting it I was thinking of removing those frames. I still might, since it is my favorite core display.
