### ISSUE TITLE
Drones can't slip into number of station doors

### ISSUE THREAD

**Issue by Ratvar** [OracleStation/OracleStation#1090]
1. Genetics - morgue area
2. Gravity Generator
3. Shh Library room
All those doors have no drone flap - mapping issue, I guess, because some of those doors make no sense to be inaccesible to drope

**Comment by AffectedArc07** [comment]
The reason for library and morgue is because them doors are mapped as centcomm doors, which makes them have protection. Same with the door for gravgen, if it has protection, it has noflap
