### ISSUE TITLE
Goliath Tentacle Speed not adjusted

### ISSUE THREAD

**Issue by EldritchSigma** [OracleStation/OracleStation#113]
Alright current playtest, cant do anything. You have trouble dodging one goliath with tentalces if you dont have the timing straight. Try 3... impossible. Movement speed too low. Or tentacles too fast rather. Should have a delay just like Bubblegum and Ash Drake got.

**Comment by ktoma36** [comment]
Something I have also noticed is that goliaths react much faster to someone near them in terms of lashing out. Considering most ghost roles on lava land have only rudimentary melee weapons available to them it is extremely challenging to make it out of a fight without getting hit at least a few times.

**Comment by EldritchSigma** [comment]
If thats proven to be an issue I can adjust their movement speed too (Once I figured out if lower numbers mean faster or slower)

**Comment by ktoma36** [comment]
Is their attack speed affected by their movement speed?
