### ISSUE TITLE
the red security cap has a slightly different color than the uniform

### ISSUE THREAD

**Issue by FlattestGuitar** [OracleStation/OracleStation#1139]
I won't paste a pic, you have to believe me.

This is **AWFUL**

**Comment by AffectedArc07** [comment]
Flattest, can I tell you about this nice little keyboard key
![image](https://user-images.githubusercontent.com/25063394/43738613-2a604814-99bd-11e8-9801-e8452dd32a8f.png)
Since you have sharex, you just drag an area, then press CTRL+V to paste!
