### ISSUE TITLE
LOOC issues with AI

### ISSUE THREAD

**Issue by LuamTheElf** [OracleStation/OracleStation#115]
LOOC doesn't seem to work for AI, not from eye or main mob.

What happens when attempted is: Nothing shows, you can use the verb, but after you type in what you want, it just disappears with nothing happening playerside. 

After being carded the AI can LOOC in carded form.

**Comment by LuamTheElf** [comment]
@flattest

**Comment by SamHPurp** [comment]
@FlattestGuitar

**Comment by AffectedArc07** [comment]
I couldnt use LOOC at all, even as a crewmember

**Comment by Birdtalon** [comment]
@AffectedArc07 did you have it switched off?
