### ISSUE TITLE
Chem machine bug

### ISSUE THREAD

**Issue by LeRuffleFace** [OracleStation/OracleStation#1197]
Round ID: 4196

After you crowbar a chem machine after screwdriving it the frame parts and board all vanish as if they didn't exist in the first place.

**Comment by SamHPurp** [comment]
@steamp0rt - caused by #1152 I assume

**Comment by steamp0rt** [comment]
`default_deconstruction_crowbar` is used to deconstruct.

**Comment by steamp0rt** [comment]
I think I may have found the cause
