### ISSUE TITLE
Cactus fruit taste like name

### ISSUE THREAD

**Issue by ktoma36** [OracleStation/OracleStation#127]
Round ID 70. 
After wondering around slaying monsters as an ashwalker I decided to scavenge up some cactus fruit for a quick snack. Little did I know that it would taste like the literal manifestation of name.

You bite the cactus fruit.

You can taste name and fruity mushroom.

**Comment by Birdtalon** [comment]
Well I never, I'll know what to go for when I want to taste name.

**Comment by imsxz** [comment]
I've been digging and I can't find what would have made it taste like "name", cactus fruit has 3 reagents and none of them have that taste :thinking:

Even if they didn't properly define their tastes, the base reagent is still "metaphorical salt" and not "name". Hmm, I'll mess around with some foods when I get home, I suppose.

**Comment by Birdtalon** [comment]
@imsxz 

Check the reagents on here, you'll find that one of them is missing a taste description as well as its parent.

```
/obj/item/reagent_containers/food/snacks/grown/ash_flora/cactus_fruit
	name = "cactus fruit"
	list_reagents = list("vitamin" = 2, "nutriment" = 2, "vitfro" = 4)
```

**Comment by imsxz** [comment]
Vitamin and nutriment both inherit "generic food" from consumable, no?

**Comment by Birdtalon** [comment]
Yeah I'm looking a bit deeper into it now. You're correct.

**Comment by EldritchSigma** [comment]
How about "You can taste ash, Cactus Stingers and fruitloops"

**Comment by ktoma36** [comment]
Also something that I need to test more is that I think that the fruit does toxin damage to slime people. I would need to test it on its own though, I was exploring the lava lands when I noticed my toxins rising.
