### ISSUE TITLE
Cyborgs can drop bolts on depowered airlocks

### ISSUE THREAD

**Issue by ktoma36** [OracleStation/OracleStation#128]
Round ID 70. 
Saw an emmaged borg dropping bolts on depowered airlocks. With no power the bolts couldnt be raised, essentially making them impassable objects. This was an issue when the escape shuttle hallway was bolted down, preventing anyway from getting on the shuttle save the two tators and the emmaged borg.

**Comment by Birdtalon** [comment]
The same can be done when hacking a de-powered door. I'm not sure this is so much a bug and more a case of whether we want silicons to be able to interact with de-powered doors.

**Comment by SamHPurp** [comment]
Dropping bolts with wires while unpowered is - in my mind - a feature.

Borgs though, probably not.

**Comment by ktoma36** [comment]
They can do it from a distance as well. Having the bolts drop if you hack an unpowered door is alright, having a borg be able to remotely interact with the bolts of an unpowered door is kinda not. Also when the shuttle arrived the power kicked on for a few seconds. Apparently the borg was also able to set the airlocks to shock people as well.
