### ISSUE TITLE
Muzzle doesn't stop scream noise

### ISSUE THREAD

**Issue by imsxz** [OracleStation/OracleStation#149]
I had a muzzle on and did *scream, it gave the proper message for screaming while mute in chat (*makes a loud noise* or something), but the scream noise still played.

May be the same for other types of muting, idk though. I didn't fuck with any variables either iirc.

**Comment by Birdtalon** [comment]
👌

**Comment by imsxz** [comment]
To follow up, perfluro didn't stop me from screaming normally either. Didn't even give the correct message for screaming while silenced.
