### ISSUE TITLE
Ninjas can get objectives to kill themselves

### ISSUE THREAD

**Issue by imsxz** [OracleStation/OracleStation#154]
![image](https://user-images.githubusercontent.com/202160/31801249-ae7fd006-b53e-11e7-9db8-ea441af9b31b.png)

kms 😅 🔫

**Comment by SamHPurp** [comment]
Feature

**Comment by imsxz** [comment]
Is the ninja event ever even used? They're pretty fun to play as, from what I've experienced in the 10 minutes I dicked around as one on a private server.

**Comment by ktoma36** [comment]
Please tell me our ninja's actually have full invisibility, I have played on servers where it still showed a bit of your sprite and it was just bleeeeh

**Comment by FlattestGuitar** [comment]
This only occurs when you ninja a command member, which makes no sense. Not an issue.
