### ISSUE TITLE
OmegaStation AI Chamber door is called "MiniSat Chamber"

### ISSUE THREAD

**Issue by Joseph-Case** [OracleStation/OracleStation#157]
ID: 88

Not really a gamebreaker, but ruined my immersion.

**Comment by Birdtalon** [comment]
It's supposed to be the AI Minisat though isn't it?

**Comment by SamHPurp** [comment]
It is called the AI Mini sat.

This is the case on TG, and Paradise etc. Thats it name yo.

**Comment by SamHPurp** [comment]
OH RIGHT ON OMEGA YOU ARE RIGHT

**Comment by SamHPurp** [comment]
Let this get autoclosed when merged.
