### ISSUE TITLE
Broken bones don't injure you if you're being dragged

### ISSUE THREAD

**Issue by SamHPurp** [OracleStation/OracleStation#160]
Broken bones should injure you when dragged, not just when you move yourself.

The exception to this is with canes / wheelchairs and roller beds etc....

Currently if you're being pulled your broken bones are fine!

**Comment by FlattestGuitar** [comment]
I specifically made them not do that. The same way it works on Paradise.

Balance issue, but not a bug or oversight. >:C

**Comment by SmokingKilz** [comment]
I don't see why you specifically did that. If someone dragging someone else with broken bones, they should get damaged imo.
