### ISSUE TITLE
Default Lawset says "Humans" instead of "Crew"

### ISSUE THREAD

**Issue by Ziiro** [OracleStation/OracleStation#168]
With non-human species allowed in command, this could obviously cause problems.

**Comment by SamHPurp** [comment]
On TG thats intentional.

Its not a bug persay, but something we should discuss.

**Comment by Ziiro** [comment]
Oh, yeah. I know /tg/ has a thing against the lizards (and actually I think they're not actually allowed into command roles, iirc?)

I think it would be worth changing if you expand on the number of non-human options. Otherwise the AI may as well be unlawed.

**Comment by SamHPurp** [comment]
Intentional design decision to leave it as it is at the moment, and we can revisit in future.
