### ISSUE TITLE
Omega Station Issues

### ISSUE THREAD

**Issue by Xantholne** [OracleStation/OracleStation#172]
Omega Station Issues

Two Cryo Beakers in Medical
No Wrench in Medical
Not enough Medical clothing available (i.e. Belts)
Robotics lacks a proper R&D Console for syncing
R&D Lacks any toolboxes
Robotics lacks a "Limb Painter"
There is only one Plasma Canister on the entire station
Chef does not have a grill

Non specific
No RD Closet for Traitor Obj Reactive Teleport Armor
No CMO Closet for Traitor Obj Hypospray/Compact Defib
No CE Closet for Traitor Obj Advanced Magboots/Blueprints
No HOS Closet for Traitor Obj HOS Recreational Laser Gun
No Documents File for Traitor Obj Top Secret Documents

**Comment by Ziiro** [comment]
Robotics also lacks the "Limb painter" that is present in the larger robotics labs, used for augmentation. You could probably remove one of the exosuit fabs and put it there, as having two exosuit fabs seems excessive.

There is only one plasma tank on the **_entire station_** - meaning if one gets accidentally released, you can't really work the engine.

Chef lacks a grill to cook with

**Comment by Xantholne** [comment]
Updated

**Comment by SamHPurp** [comment]
Atmos console has density set to 0

**Comment by SamHPurp** [comment]
- [X] Two Cryo Beakers in Medical
- [X] No Wrench in Medical
- [X] Not enough Medical clothing available (i.e. Belts)
- [X] Robotics lacks a proper R&D Console for syncing
- [X] R&D Lacks any toolboxes
- [ ] Robotics lacks a "Limb Painter"
- [ ] There is only one Plasma Canister on the entire station
- [ ] Chef does not have a grill
- [X] Atmos console in atmos office has density set to 0
- [X] Cameras across the whole station need reviewing and replacing.

**Comment by SamHPurp** [comment]
Grill isn't a thing on TG/Oracle

I couldn't find what you were talking about via RE: Limb painter

One plasma canister is enough - order more from Cargo. Omega doesn't have redundancies.

**Comment by Ziiro** [comment]
I'm an idiot: It's actually called an "augment manipulator". (obj/machinery/aug_manipulator). Sorry about that.
