### ISSUE TITLE
Slimepeople can survive without livers, and won't process chems if lacking one.

### ISSUE THREAD

**Issue by Ziiro** [OracleStation/OracleStation#187]
You feel nauseous (and it spams your chatbox), but it doesn't have any mechanical effect because of slime's "TOXINLOVER" tag.

Fun potential side effect:
Remove a Slime Cultist's liver to make them holy water immune.

**Comment by ktoma36** [comment]
Wouldnt that also make alcoholic drinks extremely potent on them?

**Comment by taukausanake** [comment]
Wouldn't a creature based completely off water **_cough Skrell cough_** be extremely weak to alcohol? I think it would make sense but I don't know. Never had an example where slimes ever consumed alcohol. I'd imagine it wouldn't bother them because liquids are weird and stuff
