### ISSUE TITLE
Maybe a devil bug

### ISSUE THREAD

**Issue by imsxz** [OracleStation/OracleStation#198]
https://i.gyazo.com/c963be0930ca28df0ecbb9afbb7b76f0.png

Round ID 160
I spawned in as an Imp by clicking on the devil, everything was fine, ended up reconnecting and ended up with the above image as my screen. I could only hear certain noises such as the SM shard exploding. Dying fixed it. I literally have no idea what went on there.

**Comment by Ziiro** [comment]
https://github.com/tgstation/tgstation/pull/31299
