### ISSUE TITLE
Space lit overlays

### ISSUE THREAD

**Issue by SamHPurp** [OracleStation/OracleStation#25]
Weird overlay glitch in space on Omega station

![image](https://user-images.githubusercontent.com/7415122/30523528-bf5784d2-9bda-11e7-8424-d88e5ce114dc.png)

@Citinited think this is something you might be able to have a look at? Lights the overlays kinda weirdly.

**Comment by AndrewMontagne** [comment]
![image](https://user-images.githubusercontent.com/202160/30525152-5a2c0942-9bf9-11e7-8666-17c9b487b2d6.png)

Also happens as an AI when it's in the fog of war

**Comment by Citinited** [comment]
I shall take a look at it 👍

**Comment by SamHPurp** [comment]
@AndrewMontagne is this not still a problem?
