### ISSUE TITLE
Cargo crate points don't get counted properly.

### ISSUE THREAD

**Issue by FlattestGuitar** [OracleStation/OracleStation#298]
I sent three crates back, got points for one crate.

Ridiculous.

**Comment by SamHPurp** [comment]
Sure they didn't just add the numbers together? I've had this fine in the past.

**Comment by FlattestGuitar** [comment]
I can't recreate this, but yesterday I 100% had it happen to me. I sent back two crates with approved manifests and only got points for one crate and one manifest.

**Comment by SamHPurp** [comment]
I think you fucked up
