### ISSUE TITLE
Defibs are mostly worthless, Patches are not an on touch heal

### ISSUE THREAD

**Issue by Xantholne** [OracleStation/OracleStation#301]
This unfortunately makes it so patches do not apply an on touch healing making anyone with more than 200 damage defibbable and autamatically needed to be cloned.

This also does the same thing with bruise packs and burn packs. You cannot apply them specifically to the person because they are dead

**Comment by EldritchSigma** [comment]
Fixed it. Check the coder chat.

**Comment by EldritchSigma** [comment]
#444

**Comment by ma44** [comment]
This kills the cloning.
