### ISSUE TITLE
Unable to dig lavaland floors

### ISSUE THREAD

**Issue by Quantum-M** [OracleStation/OracleStation#325]
While in lavaland, I was unable to dig up any of the dirt tiles (volcanic rock that is) to get any sand. I tried both a pickax and a shovel (and even with a crowbar) with no results.

**Comment by imsxz** [comment]
nanotrasen packed some extra tough basalt for the miners this time

**Comment by Quantum-M** [comment]
Clearly, they won't want NT to see the true nature of lavaland... (#324)

**Comment by SamHPurp** [comment]
Duplicate of #324
