### ISSUE TITLE
Headset irrepairable after EMP Blast, transmits all messages into common. Bug or Feature? (TM)

### ISSUE THREAD

**Issue by EldritchSigma** [OracleStation/OracleStation#386]
Yeah had this happen multiple times now: You get emped and your headset is fried. Pretty logical, yes. It turns off all channels, shuts it down completly. Now if you try to turn back on you basicly got a headset that transmits all of that what you say into common channel and the selected channel which can be a pain in the ass to manage. Yes, even if you dont use your headset by doing "say; something" and just say "say Hey Mister Shadowling we are going to have some fun~" There is only a limited supply of headsets of some types and no way to repair them as far as I am aware.

As I said I am not sure if its intended that an emped headset is permanently in Microphone mode, seems rather weird. It also trickled in with one of the more recent ports if I recall correctly, initially it scrambled your channel, turned it off but was fixable before.

**Comment by FlattestGuitar** [comment]
99% sure the EMP turned on the SBR in your emergency box.

**Comment by EldritchSigma** [comment]
Woops I am dumb... theres a damn SBR in your box.
