### ISSUE TITLE
IPCs hallucinate from the SM.

### ISSUE THREAD

**Issue by Joseph-Case** [OracleStation/OracleStation#411]
Issue reported from Round ID: 360 (Oracle Station | Medium RP)

Played as an IPC Engineer
Set the SM up
Got hallucinations

**Comment by SamHPurp** [comment]
@Ziiro

**Comment by Ziiro** [comment]
Working on it.

I believe that the supermatter is the only thing that can do this.

**Comment by Joseph-Case** [comment]
Probably is because Inp only hallucinated as an IPC on para after an SM failure
