### ISSUE TITLE
Shuttle Vote doesnt occur at 14:00

### ISSUE THREAD

**Issue by Joseph-Case** [OracleStation/OracleStation#412]
Issue reported from Round ID: 360 (Oracle Station | Medium RP)

Issue is what it says on the tin
**What I expected:** Shuttle call vote

**What I got:** Nothing

**Steps to reproduce:** Start server, wait till 14:00, notice lack of shuttle

**Comment by SamHPurp** [comment]
Feature request. One I'd like, but its not an issue.
