### ISSUE TITLE
Revenant Respawning

### ISSUE THREAD

**Issue by The-Driker** [OracleStation/OracleStation#420]
When a revenant is killed and it's ashes are not destroyed, instead of another player being given the chance to spawn as the new revenant, it instead automatically respawns the previous revenant player as the new revenant

**Comment by SamHPurp** [comment]
That is how it works. Whats the issue here?

**Comment by The-Driker** [comment]
The description somewhat makes it seem like that isn't the case.

> If your essence hits zero, you die, leaving a pile of blue dust that will regenerate into **a new revenant** within a minute if not scattered.
> 
When it says a new revenant, I imagine a **new** revenant, being someone else, instead of the old revenant.

**Comment by SamHPurp** [comment]
Nope, thats your interpretation; I don't necessarily agree with changing it, but it would be a feature request and not an issue.
