### ISSUE TITLE
IPCs take eye damage from welding

### ISSUE THREAD

**Issue by Joseph-Case** [OracleStation/OracleStation#434]
Issue reported from Round ID: 376 (Oracle Station | Medium RP)

Issue is what it says on the tin

**Comment by Ziiro** [comment]
If I offer flash protection on standard IPC eyes, then the welding shield eyes become useless, because the IPC eyes offer the same thing and have to be able to be built baseline at the mechsuit fab.

I can do that, but I don't think I should.

**Comment by SamHPurp** [comment]
Feature request, if anything.
