### ISSUE TITLE
[MetaStation] Paramedic EVA Helmet makes head bald/default

### ISSUE THREAD

**Issue by Ralta** [OracleStation/OracleStation#451]
Putting the Paramedic EVA Helmet on causes the helmet sprite to be invisible on the head, and the actual head to be a bald human male's head. 

Have not attempted to replicate.

**Comment by TinnCatt** [comment]
Yep, I can confirm this.
![image](https://user-images.githubusercontent.com/35948390/35549730-ed1cf058-0554-11e8-9399-a015f920ab58.png)
