### ISSUE TITLE
Armless people appear to have arms when standing sideways

### ISSUE THREAD

**Issue by SamHPurp** [OracleStation/OracleStation#458]
Round ID: 403

Have no arms, but stand sideways and they appear on your character model...!

![image](https://user-images.githubusercontent.com/7415122/35472119-0ab8afee-0361-11e8-8c81-b6c61c8d9ae1.png)

![image](https://user-images.githubusercontent.com/7415122/35472128-2255c6c8-0361-11e8-8963-f386fcceae4d.png)

**Comment by FlattestGuitar** [comment]
That's a hole in the uniform sprite. Every single server ever does that.

**Comment by Ziiro** [comment]
/tg/ tried to fix this and then had to revert it like an hour later. Honk.

**Comment by SamHPurp** [comment]
Got a PR link for me @Ziiro ?

**Comment by Ziiro** [comment]
@SamHPurp This was the PR I was thinking of, but I guess it does something different than what I thought
https://github.com/tgstation/tgstation/pull/34782
https://github.com/tgstation/tgstation/pull/34966

Also I guess it was fixed?
https://github.com/tgstation/tgstation/pull/34973
