### ISSUE TITLE
Blueshield appears under civilian on the manifest.

### ISSUE THREAD

**Issue by AffectedArc07** [OracleStation/OracleStation#479]
Issue reported from Round ID: 420 (Oracle Station | Medium RP)

![image](https://user-images.githubusercontent.com/25063394/35482408-99ee06e8-042c-11e8-98d1-89fbee8639fd.png)

**Comment by SamHPurp** [comment]
They are a civilian. They aren't part of command... they're a bodyguard hired by CC specifically for Command staff - but they are by no means Command. And even less are they Security.
