### ISSUE TITLE
Miner Kinetic Accelerator Breaks

### ISSUE THREAD

**Issue by TheRespectedMan** [OracleStation/OracleStation#484]
As the title says the gun tends to break. 
https://i.imgur.com/6mbLaMW.png
Note the floating hit and KA flash sprites, they tend to signify the fact that the gun is now broken and will not reload until the broken sprites disappear. 
Me and a fellow miner had to resort to melee on this NPC miner and we got wrecked because of it.

**Comment by Ziiro** [comment]
It's a lag thing. You just have to run when that occurs, unfortunately.

**Comment by SamHPurp** [comment]
@AndrewMontagne is this the sort of thing improved by a theoretical new box? Or anythoughts on this?

**Comment by TheRespectedMan** [comment]
Still happens.
