### ISSUE TITLE
MetaStation showcase mechs missing (sprites)

### ISSUE THREAD

**Issue by Ziiro** [OracleStation/OracleStation#486]
How it should look:
![dreammaker_2018-01-28_18-59-37](https://user-images.githubusercontent.com/26494679/35490532-6f3b95b0-045d-11e8-879c-90814f66e060.png)

How it actually looks:
![dreamseeker_2018-01-28_18-54-23](https://user-images.githubusercontent.com/26494679/35490418-c01a7e2a-045c-11e8-9725-0ad920ea14ee.png)
(Yes, they're there, I confirmed with a right click. Sprites are missing.)

**Comment by Xantholne** [comment]
The sprites for the other side of the exhibit are also missing where the cloning pod and loyalty implanter case are.

**Comment by Ziiro** [comment]
![dreammaker_2018-01-28_19-21-25](https://user-images.githubusercontent.com/26494679/35490951-7b676460-0460-11e8-8099-a8a5910efa20.png)
![dreamseeker_2018-01-28_19-17-16](https://user-images.githubusercontent.com/26494679/35490956-877be3ca-0460-11e8-8df1-f845866a439f.png)

🤔

**Comment by AndrewMontagne** [comment]
The `icon` var gets set to null on the live server for some reason. Doesn't when running locally. Might be a hosting on Linux issue.

I guess in the interim we can remove them, or copy the appropriate sprites to the showcase `.dmi` and remove the var edit in the map.

**Comment by miniusAreas** [comment]
@AndrewMontagne 512 has fixed this, issue is no longer a issue
