### ISSUE TITLE
Genetics system doesn't cause mutations/ Hides SE on monkeymen.

### ISSUE THREAD

**Issue by sgtmanguy** [OracleStation/OracleStation#488]
RoundID-437
Time-All shift.
Date- 1/29/18 (mm/dd/yy)

Problem A- The genetics system seems to be unable to cause any form of mutation. Tested on the majority of blocks. Works as expected otherwise.
Problem B- Monkeys loose their SE when converted to humans. Cannot be re-obtained without using a SE from something else.

**Comment by Keluandrie** [comment]
Encountered this today. Genetics does exactly nothing at present.
