### ISSUE TITLE
Uncanceled slippery.

### ISSUE THREAD

**Issue by SideCat** [OracleStation/OracleStation#493]
Issue reported from Round ID: 445 (Oracle Station | Medium RP)

Appereantly, there's a bug at perma, that if you're going to get slipped in shower by shower's water, you won't be able to stand up at any circustances. https://imgur.com/a/IgNRA

**Comment by SamHPurp** [comment]
This is when buckets stop processing for ticks and have to rebooted automagically... there is something going on in the processor.

**Comment by SamHPurp** [comment]
I think the thing breaking this is the same thing that breaks #484
