### ISSUE TITLE
No chat disclaimer a laser tag gun was fired, unless someone hit by it

### ISSUE THREAD

**Issue by Eddlicious** [OracleStation/OracleStation#497]
Issue reported from Round ID: 447 (Oracle Station | Medium RP)

**Problem:** A laser tag gun when fired does not show "X fired a laser tag gun" in chat, unless a laser tag gun beam hits someone. This is problematic for mostly security, since many have very itchy trigger fingers and like to response to red lasers being shot their way with lethal fire.

**How to replicate the bug:** Have an X and Y person standing apart from one and other, and have the other person fire a laser tag gun past them without hitting (not sure if the laser tag gun's type matters, aka color-wise).

**Comment by SamHPurp** [comment]
I'm missing what the problem is with this?
