### ISSUE TITLE
as a floating posi brain i can hear changling channel. 

### ISSUE THREAD

**Issue by enderman51505** [OracleStation/OracleStation#498]
Issue reported from Round ID: 453 (Oracle Station | Medium RP)
i think it happened because i got destroyed as a borg by the ai and since i was made one by surgery while a ipc.

**Comment by Ziiro** [comment]
Can confirm this is a reproducible bug:

![dreamseeker_2018-01-29_18-58-04](https://user-images.githubusercontent.com/26494679/35544213-815b3394-0526-11e8-8b8a-ceb5c14f7c4f.png)

I'm working on it, but I make no promises.
@FlattestGuitar this is pretty serious

**Comment by AndrewMontagne** [comment]
Duplicate of #501
