### ISSUE TITLE
Can't buy the "Build your own shuttle kit."

### ISSUE THREAD

**Issue by Ziiro** [OracleStation/OracleStation#499]
"You have not met the requirements for purchasing this shuttle."

Not sure why this is. Weird.

**Comment by Ziiro** [comment]
DUHHHHH. WHY DON't GO TO LOOK AT THE CODE, ZIIRO

https://github.com/OracleStation/OracleStation/blob/4367101b68c2710ab25d2faad29751e74ba0db39/code/datums/shuttles.dm#L52-L54

**Comment by ike709** [comment]
I mean you should probably add some feedback for this so people who don't look at the code know why they can't buy it...

**Comment by SamHPurp** [comment]
Agreed with @ike709 

This should provide feedback to the attempted purchaser

**Comment by AndrewMontagne** [comment]
Why is this time locked in the first place?

**Comment by ike709** [comment]
I assume it's so that people have an opportunity to actually build the shuttle instead of just getting cucked near round end.

**Comment by SamHPurp** [comment]
Yeah, it -should- be timelocked.
