### ISSUE TITLE
Crawling into a vent causes Byond to crash

### ISSUE THREAD

**Issue by Eddlicious** [OracleStation/OracleStation#500]
Issue reported from Round ID: 454 (Oracle Station | Medium RP)

This occurred when:
- I was a red adult slime
- There was a massive scale plasma fire going on

**Comment by ike709** [comment]
What's your BYOND version?

**Comment by Eddlicious** [comment]
512.1405 when this occurred.

**Comment by SamHPurp** [comment]
Tried to reproduce, and was unable.... any more info?

**Comment by ike709** [comment]
I assume this is a bug involving 512 instability. Which is why I asked for the BYOND version.

**Comment by ike709** [comment]
According to #617 this occurs on 512. Therefore, I think it's just a BYOND bug like all the other crashes on 512.

**Comment by ike709** [comment]
Tested it and it definitely doesn't crash on 511.
