### ISSUE TITLE
Postronic and MMIs can hear psionic channels

### ISSUE THREAD

**Issue by Xantholne** [OracleStation/OracleStation#501]
Postronic and MMI brains when a player is inside of them can hear any sort of psionic hivemind such as changelings, abductors, and so forth.

Step 1: Make a brain
Step 2: Someoone become brain
Step 3: Overhear changeling hivemind/abductor hivemind whatever
Step 4: Get Admin PMed about possible metagaming but turning out to be a bug.

**Comment by Ziiro** [comment]
Known https://github.com/OracleStation/OracleStation/issues/498

Good to know it's MMIs as well though. Hmmmm.

**Comment by Xantholne** [comment]
:dagger:
