### ISSUE TITLE
Supermatter and atoms problems

### ISSUE THREAD

**Issue by Slomacz** [OracleStation/OracleStation#503]
Supermatter is lagging with sending out the warning messages, also it does not appear on the monitoring computer or the tablet . Not reacting to gasses how it should be. Also whole atoms system feels kinda outdated. To fix it I just suggest to merge (or copy and paste [?]) the whole TG atoms. Since It got major rework at around 10.17 . Thats all folks

SM is not reacting to gasses like If you put more Cooled N2 and more N2O It's still destabilizes the same way and at the same point if there was only only 2 cans worth of gas in it. There also seems to be problem with Gasses Heat dispensing I dont relly Know How to name it but gasses get warmer much much faster than they should

**Comment by AndrewMontagne** [comment]
Without further elaboration, closing this issue.
