### ISSUE TITLE
IPCs can be roundstart changelings

### ISSUE THREAD

**Issue by Xantholne** [OracleStation/OracleStation#512]
Issue reported from Round ID: 469 (Oracle Station | Medium RP)

Clown was a roundstart IPC changeling
Fucking what?

>Be IPC
>Set changeling to on
>Roll changeling antag round

**Comment by Ziiro** [comment]
requesting **FUCK** tag

I'm looking into it.

**Comment by Ziiro** [comment]
https://github.com/OracleStation/OracleStation/blob/6d416a974c1eb861dc4eff5e9c50226d50310bf4/code/game/gamemodes/game_mode.dm#L336-L339

🤔
