### ISSUE TITLE
ChemMaster 3000 window won't open on click

### ISSUE THREAD

**Issue by Eitz** [OracleStation/OracleStation#513]
Issue reported from Round ID: 470 (Oracle Station | Medium RP)

I started making some chems and after 3 or 4 usages, it wouldn't open its window when I clicked on it. Only one (the bottom one) had this behavior. The other worked as expected.

**Comment by SamHPurp** [comment]
Did power go out? Was this a persistant problem? Has this been re-produced, and any admins able to weigh in on anything that happened that round that might be illuminating?

**Comment by Eitz** [comment]
> Did power go out?

No, the other chem was working.

> Was this a persistant problem?

Only had it in one round.
 
> Has this been re-produced, and any admins able to weigh in on anything that happened that round that might be illuminating?

Unfortunately, no. I didn't call for any admins at the time, just made this ticket.

I am sorry for such a shallow report. Hopefully something in the logs will show up. I reported it exactly at the time of the bug (maybe this will help to track something in the log).

More details: the html window wouldn't show up on click (nothing happened, nothing in chat too), the chem had a beaker inside.
