### ISSUE TITLE
A SQL error occured during this operation, check the server logs (lost playtime?)

### ISSUE THREAD

**Issue by Ziiro** [OracleStation/OracleStation#514]
Round 471

![2018-01-30_20-20-27](https://user-images.githubusercontent.com/26494679/35603564-254b44f6-05fb-11e8-884b-97980706dd79.png)

My character data was still there, though, and there were no times for the species.

![2018-01-30_20-22-45](https://user-images.githubusercontent.com/26494679/35603662-8fcdf382-05fb-11e8-8257-4c92ebf766ec.png)

Seems to correct itself once the round actually started

**Comment by Xantholne** [comment]
It's been happening to a lot of people recently.
