### ISSUE TITLE
Posibrains from IPCs inserted into other chassis stop functioning and cannot be reinserted if removed

### ISSUE THREAD

**Issue by Nonsignificant** [OracleStation/OracleStation#515]
Round 471/472, not sure due to server issues. (sorry)

Was swapping posibrains between a cyborg and an IPC. The swap of the posibrain from the IPC to the cyborg worked fine, but when attempting to insert the cyborg's posibrain into the IPC things broke. The surgery succeeded and the posibrain was able to talk through the IPC, taking its name, but was unable to move, even after cover was closed. I started surgery again and removed the posibrain, and it came out labelled as the original chassis owner. The posibrain was also able to speak. However, it could not be reinserted into the chassis, and I was informed that it was inactive, even though the player was actively speaking.

To reproduce, attempt replacing the posibrain of an IPC with another one.

**Comment by Ziiro** [comment]
So the second part of that - the posibrain inheriting the chassis name - is logical behavior, because a posibrain stops existing when it's inserted into a chassis and a new one is created when it's removed.

However, the behavior of not being able to control the body is mysterious and I'm going to go check into it

**Comment by Ziiro** [comment]
![dreamseeker_2018-02-07_16-14-33](https://user-images.githubusercontent.com/26494679/35946711-165745e4-0c22-11e8-93f3-f3c0823ac339.png)

It's turning into a posibrain properly, but it's not actually giving them control of the body. None of the usual interface pieces appear when transplanted - but the mob is definitely alive. It stands up like it's revived (and it died when I did VV drop organ on the brain)

Hmmm
