### ISSUE TITLE
Genetics Computer losing the Strucural Enzymes section.

### ISSUE THREAD

**Issue by Soundwavesghost** [OracleStation/OracleStation#517]
Issue reported from Round ID: 481 (Oracle Station | Medium RP)

Noticed that when I converted a monkey to a human tha the SE blocks all vanished. Even tried with a second station with the monkey UI&SE saved and it lost it permanently as well.

![image](https://user-images.githubusercontent.com/5963543/35645821-35a79020-069b-11e8-8b01-c2a0e25d8a5f.png)

**Comment by SamHPurp** [comment]
Duplicate of #488
