### ISSUE TITLE
Chat spam is terrible

### ISSUE THREAD

**Issue by Nickmun0** [OracleStation/OracleStation#538]
Theres 0 need for chat to end up filled with combat logs repeatedly, I happen to have frozen multiple times from it and I'm sure others have too, over all just a trashy down side to this server.

**Comment by ike709** [comment]
Port the TG thing that combines the same message into one and add x2/x3/x4/etc to the end of the message.

**Comment by SamHPurp** [comment]
Feature request, not a specific issue.

I do support porting TGs one, but I highly dislike the size increase thing TG do with it.

**Comment by ike709** [comment]
TG removed the size increase @SamHPurp

**Comment by ike709** [comment]
https://github.com/tgstation/tgstation/pull/35058/files

**Comment by SamHPurp** [comment]
Good, that was literally my feedback on TG's original PR for it :P
