### ISSUE TITLE
Bartenders lack Mineral Storage access

### ISSUE THREAD

**Issue by Xantholne** [OracleStation/OracleStation#559]
Title.

Can't get muh uranium for my atomic bombs, and nuka colas

**Comment by SamHPurp** [comment]
Why would they need access to everything? Barter for it yo.

**Comment by FlattestGuitar** [comment]
I am of the opinion they don't need the access. If they want uranium they have to fight for it.

**Comment by TheRespectedMan** [comment]
Bartenders on paradise have access to the orm so they can get the uranium they need for some nuka cola.

**Comment by scrubmcnoob** [comment]
Seems more like a gimmick gone too far. They should have to actually /talk/ with others to get the ores, not just be able to access the machine. They can also just take everything else out just because they got access.
Doesn't make sense for the role to have access to the ORM.

**Comment by SamHPurp** [comment]
Be a big boy, use your words.
