### ISSUE TITLE
Syndicate uplink 'Random Item' shows cost of 0TC

### ISSUE THREAD

**Issue by Ralta** [OracleStation/OracleStation#56]
Round ID: 35

Played as Cargo Tech syndicate agent. Used the PDA uplink and saw 'Random Item' showing cost of 0TC. It did not cost 0TC - I bought an emag and pizza bomb, then clicked the Random Item three times and did get three random items. Ran out of TC and couldn't order any more.

**Comment by Jovaniph** [comment]
I think the issue is that Random Item will give you something that is available for you to purchase. In other words, you bought an emag and pizza bomb which already cost you 12 TC. What else did you get?

**Comment by Birdtalon** [comment]
This isn't a bug really. It's working as intended. It shows as 0 because it won't calculate the cost until you click the button to purchase it.

**Comment by FlattestGuitar** [comment]
Not a bug. Would be nice if someone addressed this at some point, but it's not the end of the world.
