### ISSUE TITLE
Genetics Manifestations

### ISSUE THREAD

**Issue by threehornes** [OracleStation/OracleStation#562]
Issue reported from Round ID: 566 (Oracle Station | Medium RP)

Using spawned in humans, altering SE did nothing. Tried to test 3 SE's that were at e+, and using the injector had no effect aside from radiation. Even occupant:delayed did nothing, so it would appear that the effects, both negative and positive aren't registering.

**Comment by AndrewMontagne** [comment]
Duplicate of #488
