### ISSUE TITLE
Bug with Genetics.

### ISSUE THREAD

**Issue by Tatsu500** [OracleStation/OracleStation#570]
Issue reported from Round ID: 580 (Oracle Station | Medium RP)

Hi i just wanted to say that genetics has some bugs on the Meta Station, when i transform a monkey into a human, i experiment with the bodies, the SE does not show up.

And if i already have a human to experiment, when i change the SE it has no effect.

**Comment by AndrewMontagne** [comment]
Duplicate of #488
