### ISSUE TITLE
Airlocks not auto-bolting (Cargo Bay)`

### ISSUE THREAD

**Issue by Ralta** [OracleStation/OracleStation#58]
Round ID: 35

When shuttle leaves/arrives, the airlocks do not bolt/unbolt, meaning you can just open them and go for a spacewalk.

**Comment by AffectedArc07** [comment]
Things in TG code dont auto-lock iirc

**Comment by SamHPurp** [comment]
Yeah this is a wider functionality thing, not a bug.

**Comment by SamHPurp** [comment]
Feature request ported onto Trello
