### ISSUE TITLE
.45 ammo the ammo for the blueshield is invisible 

### ISSUE THREAD

**Issue by Dinopeaks** [OracleStation/OracleStation#580]
Issue reported from Round ID: 616 (Oracle Station | Medium RP)

hard to play as one if your ammo is hiding from you here is a pic 

![scrnshot1](https://user-images.githubusercontent.com/36280648/35998536-f9046ee4-0cea-11e8-906d-a7560c08cad1.png)

**Comment by ike709** [comment]
>not wearing the Blueshield holster

**Comment by Dinopeaks** [comment]
I have worn it and it still is hidden

**Comment by Dinopeaks** [comment]
![scrnshot2](https://user-images.githubusercontent.com/36280648/35998932-25ca319c-0cec-11e8-9d3b-ebc53fe0b443.png)

**Comment by scrubmcnoob** [comment]
Can't reproduce.
.45 and .38 which you both get from blueshield box are fine

**Comment by Dinopeaks** [comment]
if you use the the autolathe for a ammo box so you can refill your mag's you can not see the one of the ammo boxes show up the other will not show up
