### ISSUE TITLE
Chat Color not displaying correctly.

### ISSUE THREAD

**Issue by Arkozo** [OracleStation/OracleStation#588]
Issue reported from Round ID: 641 (Oracle Station | Medium RP)
The UI of my BYOND is being funky, and the chat only shows black text on a white background regardless of whether it's just local chatter or radio. It's very disorienting. Changing BYOND versions did not work. Running on Windows 10.

**Comment by ike709** [comment]
Pics

**Comment by Arkozo** [comment]
https://imgur.com/1U0xHFs
Like, shouldn't Common, Service, and Science all have their own colors?
