### ISSUE TITLE
Changeling group goals can get the objective to become a IPC

### ISSUE THREAD

**Issue by Xantholne** [OracleStation/OracleStation#589]
title.

1: Ensure changelings impersonate and escape as the following members of the medical department: Ark Shaffer the Virologist, Sarah Banlon the Medical Doctor, FENIX-2496 the Geneticist, John Sweeps the Geneticist, while the real members are dead. This is a team objective. 

***FENIX-2496 the Geneticist,***

**Comment by Ziiro** [comment]
iirc you can actually pull this off without having to absorb the target. You just have to do something like wear a hardsuit while wearing their ID.

**Comment by AdamElTablawy** [comment]
no, you gotta actually be the person.

**Comment by ike709** [comment]
Just add a check when picking targets to make sure they're not an IPC.
