### ISSUE TITLE
Portable chem dispensers still dispense sulfuric acid.

### ISSUE THREAD

**Issue by AffectedArc07** [OracleStation/OracleStation#592]
Pretty self explanatory

Issue reported from Round ID: 648 (Oracle Station | Medium RP)

**Comment by praisenarsie** [comment]
fucker

**Comment by AdamElTablawy** [comment]
I believe this only applies when upgraded.

**Comment by Ziiro** [comment]
Correct. Base components chem dispensers still does not have it.

**Comment by SamHPurp** [comment]
This is deemed intentional.
