### ISSUE TITLE
vent and scrubber sprites look like they were ripped from openss13

### ISSUE THREAD

**Issue by praisenarsie** [OracleStation/OracleStation#596]
![2018-02-10_16-54-25](https://user-images.githubusercontent.com/31222036/36064458-36ef0cd4-0e83-11e8-8e5b-168614752f11.png)
use the fucking classic ones or eris' ones

**Comment by SmokingKilz** [comment]
Not an issue, some sort of feature request.

**Comment by praisenarsie** [comment]
you're a feature request
