### ISSUE TITLE
Minor visual bug - items staying in hands

### ISSUE THREAD

**Issue by Vivinet** [OracleStation/OracleStation#599]
Issue reported from Round ID: 653 (Oracle Station | Medium RP)

I've been encountering a weird bug where items visually stay on the character after holding them in hand for some time. Issue persists upon death, loss of limb, re-equipping and un-equipping the items, etc. This has happened a few times before, don't know what exactly causes the issue.

**Comment by FlattestGuitar** [comment]
Duplicate of #171
