### ISSUE TITLE
Scichem is missing on Omegastation, and presumeably most other stations

### ISSUE THREAD

**Issue by EldritchSigma** [OracleStation/OracleStation#60]
As the topic says. Theres a lack of scichem on Omegastation. Probably intended for that map considering how small it is. But for the bigger maps, once the server goes life, there should be a scichem. If its intended just disregard.

**Comment by SamHPurp** [comment]
Intended for how small the map is.

Hopefully if pop increases we can begin to use larger stations (Delta & Pubby anyone? :) )

**Comment by EldritchSigma** [comment]
Ah alrighty no worries then. Delta looks pretty interesting indeed.
