### ISSUE TITLE
Health analyzer gives "Subject is bleeding" message after using gauze to heal bleeding.

### ISSUE THREAD

**Issue by ike709** [OracleStation/OracleStation#601]
Issue reported from Round ID: 657 (Oracle Station | Medium RP)

See tin. Note that I used the analyzer on myself and I still had a bunch of brute damage. I did not bleed onto the ground as I walked around after I used the gauze, so I assume it's just a problem with the analyzer itself.

**Comment by FlattestGuitar** [comment]
Well, you're still technically bleeding. Gauze doesn't stop bleeding permanently; it can fall off. It's going to say you're bleeding until you stop the cause of the bleeding.

**Comment by Ziiro** [comment]
To note: this kills ash walkers a lot, because they can only gauze it up temporarily. If they walk around and do things while gauzed, the bandage falls off eventually and they resume bleeding.

**Comment by ike709** [comment]
No but like immediately after using gauze it still says it.

**Comment by ike709** [comment]
@FlattestGuitar you fleeb see above

**Comment by SamHPurp** [comment]
Since pressure on Lavaland is different, we could concievably alter the bleeding/clotting thing while on Lavaland / altered pressure environments. 🤔
