### ISSUE TITLE
Eye surgery not working

### ISSUE THREAD

**Issue by Ralta** [OracleStation/OracleStation#605]
Attempting to repair eyes with surgery doesn't seem to work. Following the steps requires Scalpel > Retractor > Hemostat > Hemostat > Cautery. It works up until the second Hemostat requirement to repair the damage, at which point any surgery tool just stabs them. Cautery just ends the surgery as expected. 

Witnessed it occur once, then attempted it a second time to confirm the issue. Unsure what's causing it.

**Comment by SamHPurp** [comment]
(If you guys include the round ID, I can go back and check on the runtimes from that round!)
