### ISSUE TITLE
IPC brain implanting breaks

### ISSUE THREAD

**Issue by sgtmanguy** [OracleStation/OracleStation#616]
Round ID- 697

Involved ROOK-324- IPC and the deceased E.O.N- IPC

As far as I can tell, E.O.N was torn apart. Robot limbs everywhere, brain knocked out. Effectively dead, save for the active brain. ROOK attempted to implant the brain- First, into the head, then into the chest when the error was pointed out. I **believe that, even though it was implanted in the head, the brain automatically transferred itself to the chest.**
Once implanted E.O.N was temporarily revived. Stuttered when spoke. Shortly died. Had over 100 toxin, most other damage was repaired.
Death was permanent this time, and, according to E.O.N their camera was stuck on ROOK. **The corpse said that there was no soul when inspected, though E.O.N could still speak**. ROOK removed E.O.Ns IPC brain, which now read as inactive. Reset it numerous times, and eventually E.O.N could re-activate the brain. The brain was re-implanted to no avail, and the brain would read as inactive if removed then. Reset again and stuck E.O.N into a borg with no problem
After this, ROOK had a multitool sprite in each hand and a health scanner sprite in the left hand, even though their hands were empty.
Whack.

**Comment by AndrewMontagne** [comment]
Paging @Ziiro

**Comment by Ziiro** [comment]
There's a lot to unpack here, but from what I can figure this is a lot of the same bug stuff as https://github.com/OracleStation/OracleStation/issues/515

However the installing in the head is a new one. So this isn't a total duplicate.

The toxin damage comes from EMPs by the way. EMPing the substance processor does toxin damage. Clear it up with system cleaner.
