### ISSUE TITLE
Ventcrawling crashes Dream Seeker

### ISSUE THREAD

**Issue by Lorwp** [OracleStation/OracleStation#617]
Round ID 697

>Be Ventcrawling Slime

>Try to Ventcrawl

>Dream Seeker freezes after a few seconds in vent

>Reconnect. Dream seeker crashes once goonchat loads

Doubt it's goonchat, but otherwise i'm not sure what's causing this.

**Comment by Lorwp** [comment]
nevermind #500 exists

**Comment by ike709** [comment]
People not reporting their BYOND version when crash bugs happen is why crash bugs don't get fixed.

**Comment by Lorwp** [comment]
Was running the latest beta (`512.1408`) for reference. couldn't hurt to
put a BYOND version field in the issue template either.

**Comment by ike709** [comment]
All crashes that occur on 512 are presumed to be 512 instability, it has had severe issues with crashing in all versions.
