### ISSUE TITLE
IPCs who ghost Issue.

### ISSUE THREAD

**Issue by LuamTheElf** [OracleStation/OracleStation#623]
Issue reported from Round ID: 708 (Oracle Station | Medium RP)

When an IPC ghosts they cannot have their brain replaced with a posi, the posi gets stuck in the body and is still focused on the persons hand, they can still speak from the body though. Even weirder though, is when going to remove the new posi from the IPC they have the IPCs name, and are treated as inactive, their screen is black from what I heard and I think can still talk, but they when clicked begin searching for new personalities and cannot be placed into borg shells.

**Comment by ike709** [comment]
@Ziiro

**Comment by Ziiro** [comment]
This was fixed in https://github.com/OracleStation/OracleStation/pull/663
