### ISSUE TITLE
Light bolbs tiles outside mining station aren't affected by ash storm

### ISSUE THREAD

**Issue by LuamTheElf** [OracleStation/OracleStation#640]
Issue reported from Round ID: 764 (Oracle Station | Medium RP)
I stood under them too to make sure it wasn't a graphical glitch, sure enough its safe.
![oh no an ashstorm better stand next to this light](https://user-images.githubusercontent.com/26862920/36345328-3332a0c4-13f6-11e8-82b1-552e982cc1c0.png)

**Comment by SamHPurp** [comment]
Yeah its due to area definitions, and if you want those lights to be lit up, thats how its gotta work.

**Comment by LuamTheElf** [comment]
Alright, odd but I see then.
