### ISSUE TITLE
Supermatter doesnt explode

### ISSUE THREAD

**Issue by AffectedArc07** [OracleStation/OracleStation#643]
Issue reported from Round ID: 765 (Oracle Station | Medium RP)

The SM sat at 0% for ages, then just didnt explode

**Comment by SamHPurp** [comment]
Got any more info about what was happening at the time in that round?

Checked the runtimes logs for that round, and I've got nothing!

**Comment by ike709** [comment]
Was the server lagging really bad that round?

**Comment by AffectedArc07** [comment]
Not really, it seemed fine

**Comment by Bksparkie1** [comment]
This happened again last night, unsure why it occurred

**Comment by AffectedArc07** [comment]
I realksed what this is. IF the SM has no atmosphere, it cant explode
