### ISSUE TITLE
Ash Drakes Fly Attack not dodgeable with current speed.

### ISSUE THREAD

**Issue by EldritchSigma** [OracleStation/OracleStation#65]
So considering we got lowered speed and we got megafauna I thought I would try out the easiest of them. Normally with enough speed the ashdrake is manageable. You can dodge all of his attacks with the current speed but one. Thats the flying sweep, you know where he flies up into the air and stomps you if you dont dodge in time. Usually you got a second to get away which is, provided you have normal TG movementspeed absolutly doable. As it stands now its pretty much impossible. Ash Drake used his sweep 3 times on me and couldnt dodge them at all because they are always targetting the center. I suggest to fix this minor issue the ashdrake should get a small delay on his sweep attack, say 1.5 seconds. That way you can dodge his sweep if you react in time which is (near) impossible right now. Other than that the megafauna is pretty much good to fight against at the speed we now have.

**Comment by Birdtalon** [comment]
Could increase the time it takes for him to land on the flying swoop?

**Comment by EldritchSigma** [comment]
Yeah that would make it manageable. I hit him quite alot too, but the flying swoop is currently just the thing that breaks him. The fireballs and all that are not too bad aslong you keep moving.
