### ISSUE TITLE
Consoles record printing blank paper

### ISSUE THREAD

**Issue by Jovaniph** [OracleStation/OracleStation#66]
While testing with a friend on a private server. I found that printing records (Security, Medical, or ID Console) would print a clear page, but when examine you can see that the paper is written with the person's record.

This is probably just a sprite issue.

**Comment by Birdtalon** [comment]
So the paper item exists but it's missing its sprite?

**Comment by Jovaniph** [comment]
No the paper item does print. But when it prints, it prints a blank sheet of paper instead of a written one.

**Comment by Birdtalon** [comment]
Ah okay I see. Thanks.
