### ISSUE TITLE
Voxes

### ISSUE THREAD

**Issue by SideCat** [OracleStation/OracleStation#688]
Issue reported from Round ID: 1151 (Oracle Station | Medium RP)

Voxes can make IPC's sounds (*beep, *buzz *yes), voxes can't wear a tophat (wut), voxes special N20 tank doesn't count as item  and you can break anything with it nor damage someone.

**Comment by Ziiro** [comment]
Emotes are a bug, will fix.
I'll see about the top hat (and paper hat)
And the tank dealing no damage is intentional. Examine it.
