### ISSUE TITLE
SpiderOS Ninja improper arguement

### ISSUE THREAD

**Issue by Cactus2388** [OracleStation/OracleStation#709]
Round 1227:

Spawn as Ninja
"lol what the fuck is this shit"
Activate suit
SpiderOS online
Click SpiderOS tab
**Get this:**
![spiderostab](https://user-images.githubusercontent.com/27895840/37387255-aea562e6-2729-11e8-9c4f-9ceff4048633.PNG)
Armsky stunlocks me in a primary hallway
_Commit seppuku_

**Comment by ike709** [comment]
Ninja is a broken piece of shitcode in general. Either it needs to be disabled or admins need to stop dicking around.

**Comment by Ralta** [comment]
Interesting, I haven't had that happen yet and I've been playing around with the ninja a lot to figure out which parts are broken (not much from what I can see). Was there anything more specific happening? Presumably it was an event, not a bussed in Ninja?

**Comment by Cactus2388** [comment]
It was an event

**Comment by Ralta** [comment]
I've only been able to test a midround event once, so I'll see if I can mess with it some more. Just to confirm, you turned on the SpiderOS button at the top left,  then hit the tab in the UI and THAT'S when it crashed?

**Comment by Cactus2388** [comment]
Yes
