### ISSUE TITLE
Combining item stacks is broken

### ISSUE THREAD

**Issue by Sikroth** [OracleStation/OracleStation#715]
What it says in the title. Sometimes adding a stack of items to another will only add 1 item to the resulting stack (e.g. If you combine two stacks of 10 you end up with 11 items instead of 20). I'm not sure if it happens when combining held items or when they combine on the floor, I haven't payed enough attention to that.

I've experienced this issue in a number of items. Namely, from the top of my head: mining beacons, floor tiles, metal rods, metal sheets, botany cloth/leather, sandstone bricks, etc. The easiest way to reproduce it I can think of it using the biogenerator in botany.

Steps to reproduce:
- Load and process some fruits in the biogenerator (at least 1000 biomass).
- Make a x10 cloth stack.
- Without picking it up, make anoter x10 stack.
- The cloth stack on top of the biogenerator now has 11 items in it instead of 20.

**Comment by FlattestGuitar** [comment]
Nvm it does work the way you described. No bueno.
