### ISSUE TITLE
Missing Space Suit sprite for vox.

### ISSUE THREAD

**Issue by oversane** [OracleStation/OracleStation#720]
Round ID: 1289

Order a Space Suit crate from cargo (Probably isnt caused by this)
Put the suit on a vox, you can put anything else, but... eh.
Vox is now naked, gross.
Taking the space suit off will make the effect go away.

**Comment by Ziiro** [comment]
I'm going to assume it's this crate:

https://github.com/OracleStation/OracleStation/blob/c0db9c2b382007afc35192e40a05e613405ffd09/code/modules/cargo/packs.dm#L40
