### ISSUE TITLE
Vox are missing pie-face sprites

### ISSUE THREAD

**Issue by Ziiro** [OracleStation/OracleStation#722]
![unknown](https://user-images.githubusercontent.com/26494679/37558526-fd23e15a-29da-11e8-9594-3d2fe84308c8.png)

https://github.com/OracleStation/OracleStation/blob/7056b384106ef0e50cf0c8bcf9be802df4e2eef5/code/modules/food_and_drinks/food/snacks_pie.dm#L45

&

https://github.com/OracleStation/OracleStation/blob/c9e2465987b4a2e2ae62645a0012ca7032e8fde0/code/modules/mob/living/carbon/human/human.dm#L714

Should probably refactor

**Comment by Ralta** [comment]
`Not a bug`
`Working as intended`
