### ISSUE TITLE
Unable to make imitation carp fillets

### ISSUE THREAD

**Issue by swagbringer** [OracleStation/OracleStation#749]
Hi there, Im not normally a github user so hopefully you guys understand me when i work on this.

As stated in the title you cannot make imitation carp fillets using tofu and carpotoxin, the recipe just doesnt exist.

I found this on the  github
 
https://github.com/OracleStation/OracleStation/blob/7056b384106ef0e50cf0c8bcf9be802df4e2eef5/code/modules/food_and_drinks/recipes/food_mixtures.dm at line 113

Do I need to inject the carpotoxin to make it?

Im sorry if this isnt an "issue" or not, I wasnt sure where to put this. If its not too big an issue to port would someone be able to do it? Much appreciated.

EDIT: Yes an injection is needed, sorry for making this post please delete it.

**Comment by FlattestGuitar** [comment]
:3
