### ISSUE TITLE
Upon changing into a vox and then into any other race, the O2 warning never goes away.

### ISSUE THREAD

**Issue by LuamTheElf** [OracleStation/OracleStation#761]
Issue reported from Round ID: 1452 (Oracle Station | Medium RP)

I was smoking unstable mutagen toxin from an ecig, and became a vox for a second then switched again, but wasn't able to get rid of the O2 warning since it happened.

**Comment by Ziiro** [comment]
https://github.com/OracleStation/OracleStation/issues/742 Duplicate issue
