### ISSUE TITLE
Missing chemistry recipe for Oxandrolone

### ISSUE THREAD

**Issue by recatek** [OracleStation/OracleStation#763]
Chemistry/Medicine (code/modules/reagents/chemistry/recipes/medicine.dm) is missing the recipe for Oxandrolone. Listed on the [wiki](https://tgstation13.org/wiki/Guide_to_chemistry#Superior_Healing_Medicines) as:

- 3 Carbon
- 1 Phenol
- 1 Hydrogen
- 1 Oxygen

_(Sidenote: Would be nice if it was 2 carbon instead of 3 to better fit in a 100-unit beaker.)_

**Comment by ike709** [comment]
The recipe was removed during the half-assed chem rework:

https://github.com/OracleStation/OracleStation/pull/2

**Comment by recatek** [comment]
Stats-wise it's the exact counterpart to Salicylic Acid, which works fine as a recipe. Should one exist without the other?

**Comment by Ralta** [comment]
Pretty sure it should just get removed from the wiki if we have salicylic. Not sure what other reasonable function we could give Oxandrolone in the game right now.

**Comment by recatek** [comment]
They both serve a purpose without overlapping. Oxandrolone is for Burn what Salicylic Acid is for Brute. In fact it's strange for one to exist without the other.

**Comment by FlattestGuitar** [comment]
The link you gave isn't even to our own wiki. What even.
