### ISSUE TITLE
xeno larvae are wayyyy too fast

### ISSUE THREAD

**Issue by coldud13** [OracleStation/OracleStation#772]
Round: 1506

Xeno larvae run around like they're on meth. I'm guessing it's a leftover from tg movement speed.

**Comment by AdamElTablawy** [comment]
they're slower than they are on /tg/

**Comment by LuamTheElf** [comment]
Xenolarve are supposed to be the fastest mob type in the game. Because that is all they have. And sometimes the entire event is banking on their survival.

**Comment by FlattestGuitar** [comment]
Yeah, they're slower than on /tg/. They'd probably still use some tweaks, but this isn't a bug. Especially considering how rare any xeno victory is.
