### ISSUE TITLE
Cryosting doesn't work

### ISSUE THREAD

**Issue by Tomtoot** [OracleStation/OracleStation#778]
Issue reported from Round ID: 1528 (Oracle Station | Medium RP)

Unsure if maybe it has been nerfed ALOT since i last played but i stung 3 people in the round before i died and none of them were slowed, hurt or anything, it was like it injected nothing.

I ended up dying because I had to chase someone who should have been slowed due to the cryosting into a corridor

**Comment by Bksparkie1** [comment]
Cryosting takes a decent amount of time to take effect, I'm not 100% sure, but I do not think this is a bug.

**Comment by FlattestGuitar** [comment]
Cryosting does work slow as heck. 

It's pretty garbage, but it works as intended.
