### ISSUE TITLE
Blood cult target group objective assignments

### ISSUE THREAD

**Issue by SamHPurp** [OracleStation/OracleStation#787]
Apparently this has existed for ages but nobody got around to bug reporting it. This is a high priority problem.

Blood cult group sacrifice targets are getting randomly assigned to different people, when all blood cult should have the same target. This only happens mid-round, not at round-start (as far as I'm aware).

My assumption is that this is to do with our cryo-pod code, and is noting that the target cryo'd then looping all people who had them as an objective and assigning a new target at random - when actually it needs to be decided upon, then looped through and assigned.

My assumption could be false.

**Comment by vverti** [comment]
Sorry for never reporting this earlier, one thing I will note is that it seems to be that whoever the newest convert is SEEMS (not certain) to have the correct sacrifice target.

 Last night something new popped up in this issue which was the fact that, despite the sacrifice target being non-SSD/catatonic or cryoing, cult members being told, and I quote "Nar'Sie murmurs, Keith Riker is beyond your reach. Sacrifice Catherine Small instead..." While ALL the cultists still had to sacrifice their original target in their objectives. 

This makes me think that for some reason it is randomly deciding the sacrifice targets are no longer available, and so it tries to give a new objective, but never actually GIVES the new objective. 

I will update if anything new comes to light.
