### ISSUE TITLE
Credits arent centered

### ISSUE THREAD

**Issue by AffectedArc07** [OracleStation/OracleStation#789]
Issue reported from Round ID: 1548 (Oracle Station | Medium RP)

![image](https://user-images.githubusercontent.com/25063394/38167006-d72e881e-3525-11e8-8eaa-3f5d52692943.png)

**Comment by FlattestGuitar** [comment]
A bug that Dave has to fix or he doesn't get his dog treats.

**Comment by AffectedArc07** [comment]
I just realised this PR had a number flow
