### ISSUE TITLE
Bartender uniform vox sprite missing

### ISSUE THREAD

**Issue by Cactus2388** [OracleStation/OracleStation#794]
Round ID: 1560

Join vox bartender
Alt click "Bartender's Uniform" to wear it casually
can wear the suit, but there's no sprite for it.

**Comment by Ziiro** [comment]
I know how to fix this. It's just that the outfit is "missing" it's _t sprite. I can just copy+paste it, but I'm going to wait for a few more sprite issues to pop up to do them all as one big pass.
