### ISSUE TITLE
Crashing / Instability

### ISSUE THREAD

**Issue by Vivalas** [OracleStation/OracleStation#797]
So yesterday on metastation, by engineering, when I was fighting a plasma fire I kept crashing. On average it was once every 1-5 minutes until I gave up and left. I don't know the cause, but I do know this is the first time I have dealt with this kind of instability on Oracle.

I tried it on both stable and beta branches of BYOND. 

My current build is 512.1403, and I'll update the stable and stay on it and see if it happens again.

**Comment by FlattestGuitar** [comment]
We haven't gotten consistent reports of similar behavior, so I'm not sure what to make of this. I'll pin this on the beta being unstable.
