### ISSUE TITLE
Putting a slimeperson into a cryox tube removes all their limbs and kills them

### ISSUE THREAD

**Issue by Lady-Luck** [OracleStation/OracleStation#80]
Also you can't defib them!!!

You can clone them though.

**Comment by FlattestGuitar** [comment]
Intentional. Slime People deserve this.

**Comment by ktoma36** [comment]
;_; I was the slime person

**Comment by AndrewMontagne** [comment]
Considering keeping this as a Feature™, and changing the recipe for Rezadone to not require carpotoxin.

**Comment by SamHPurp** [comment]
Discussing this with Andrew, I kinda like the fact that you can't blindly throw any race into the cryopod, and his solution for clone damage makes sense to me.

What do you guys think?

**Comment by Birdtalon** [comment]
As long as there are viable ways to heal the slime person other than cryo then sure.

**Comment by ktoma36** [comment]
Also should mention the doctors said that I had no blood after coming out of the pod

**Comment by SamHPurp** [comment]
This is working as intended.

We have however altered the rezadone recipe to make it easier to fix clone damage of Slimes that way as a result of this issue report.
