### ISSUE TITLE
Guides to advanced mimicry finger bullet aiming body part targeting not working like normal guns.

### ISSUE THREAD

**Issue by Annapox** [OracleStation/OracleStation#814]
Issue reported from Round ID: 1616 (Oracle Station | Medium RP)

Guides to advanced mimicry finger bullets aiming not working like normal guns

After thorough testing against multiple targets, it seems that mime finger bullets can almost exclusively only aim for the chest, and only deal 20 brute no matter where you aim. If I could actually aim for other body parts for a higher chance based stun/avoid armor or whatever they might be worth 12 tc, but as it stands they are definitely not worth the costs all things considered, even with infinite ammo

Can the targeting issue be looked into? When a target has armor it'll actually deal less damage than a cleaver if i can only aim for the chest. 
After testing against multiple targets, I only hit something other than the chest only once or twice at point blank range, and standing three tiles away.

**Comment by FlattestGuitar** [comment]
These aren't coded like guns, they're a spell. Will not change in the foreseeable future.
