### ISSUE TITLE
Bees not getting along in the podman spawn?

### ISSUE THREAD

**Issue by Arkozo** [OracleStation/OracleStation#816]
Issue reported from Round ID: 1623 (Oracle Station | Medium RP)
So I'm new to botany, so I don't know if bees just behave like this naturally anyway (If so completely disregard and/or delete) but upon firing up the two apiary's a couple bees just started hitting them. Eventually they broke one and I killed the ones that were attacking the other, but it just seemed strange.

**Comment by FlattestGuitar** [comment]
Bees are dicks.
