### ISSUE TITLE
Invisible heat junction pipes

### ISSUE THREAD

**Issue by Captaincardgage** [OracleStation/OracleStation#827]
Round ID: 1683

Players in atmos reported invisible junction pipes, after confirmation it can be proven. Used a Rapid Piping device and tried laying heat junction pipes but their sprites were invisible.

https://i.imgur.com/S2LG05r.png?1

**Comment by The-Driker** [comment]
Investigation in game revealed that the pipes are being spawned from the RPD with the icon_state as junction2 instead of junction.

**Comment by AndrewMontagne** [comment]
Duplicate of #756
