### ISSUE TITLE
Cargo Shuttle never docks

### ISSUE THREAD

**Issue by Birdtalon** [OracleStation/OracleStation#83]
Cargo shuttle can be called but never actually properly docks.

Requires further testing to pin down. Runtime related as far as I know so far. I will update upon further testing.

**Comment by FlattestGuitar** [comment]
Likely a duplicate of #64

I'll close this for now.

**Comment by SamHPurp** [comment]
@FlattestGuitar I think you've set the wrong thing as 'duplicate of'.... thats LOOC....

But that said, I've solved the cargo problem, just sorting my repo out...
