### ISSUE TITLE
Mid-round spawned blob can't actually win

### ISSUE THREAD

**Issue by Ziiro** [OracleStation/OracleStation#835]
It doesn't have a "status" x/250, and no matter how large they get they can't win.

When you combine that with the fact that it generally puts the station under quarantine, this is a problem.

**Comment by AdamElTablawy** [comment]
Admins enforce the quarantine, somewhat unnecessarily, in that case.

Frankly, i'd say we just port the PR that makes blob midround antag only and gives it a win size.

**Comment by SamHPurp** [comment]
They shouldn't win. They should be destroyed, shuttle called, or nuked.

**Comment by AdamElTablawy** [comment]
That's a bit of a bold statement. Why shouldn't they be allowed to win like every other midround antag is?

**Comment by SamHPurp** [comment]
Name another midround antag that "Wins" causes the round to end?

**Comment by Ziiro** [comment]
Then I think as a policy we should only  be enforcing quarantine for roundstart blob. And even then, the shuttle can't be called for 20 minutes after roundstart, so it's largely moot in that case.

In essence: No more quarantine for blobs, ever.

**Comment by AdamElTablawy** [comment]
@SamHPurp Name another midround antag that, if it's successful in any case, the crew is so fucked they can't fight it and gets horribly steamrolled, but admins won't let them send the shuttle and instead send increasing amounts of ERT after it until they just set off the nuke and end the round anyway?

There's no difference there.

**Comment by SamHPurp** [comment]
@AdamElTablawy Xenomorphs?

**Comment by AdamElTablawy** [comment]
@SamHPurp 

Still not seeing a difference. Those antags being successful means everyone dies and the station is destroyed. Might as well give them a round end condition.

**Comment by FlattestGuitar** [comment]
No midround antag ever "wins". Their win is the round ending prematurely. This isn't a bug.
