### ISSUE TITLE
Wallet-ID bug

### ISSUE THREAD

**Issue by Cactus2388** [OracleStation/OracleStation#837]
Round ID: 1713

Pick up wallet
Put ID in wallet
Wallet automatically equips to the ID slot?
Wallet is invisible now
![walletmissing](https://user-images.githubusercontent.com/27895840/38474937-c05d760a-3b69-11e8-8954-d903b7d8f8e8.PNG)
Take ID out of wallet
![visiblewallet](https://user-images.githubusercontent.com/27895840/38474940-cc6a5166-3b69-11e8-93a9-092699689bd8.PNG)
When I was wearing the ID in the wallet I couldn't examine myself to see I had the wallet on.

**Comment by FlattestGuitar** [comment]
I don't know what maniac made the wallets, but they work like this on every codebase. 

The invisibility is a bug tho.
