### ISSUE TITLE
ORM eats Mining Satchel Of Holding when clicked on.

### ISSUE THREAD

**Issue by Derpyhsi** [OracleStation/OracleStation#852]
Round ID: 1847
Whats wrong:
When I try to load ores into the ORM with the Mining Satchel of Holding by clicking the ORM with the Mining Satchel of Holding it recycles the Mining Satchel of Holding into mats instead of loading the ores into the ORM.

**Comment by Bksparkie1** [comment]
repeat of #768 please close, we are aware of this bug
