### ISSUE TITLE
Cant exit from mech when controlling as an AI

### ISSUE THREAD

**Issue by AffectedArc07** [OracleStation/OracleStation#877]
Make mech
Give AI combat software
Buy mech domination
Control mech
Scream when you cant get out

Issue reported from Round ID: 2127 (Oracle Station | Medium RP)

**Comment by Ziiro** [comment]
Read "Mech Domination" very closely.

https://github.com/OracleStation/OracleStation/blob/47df647a052ccce3194ff52f985c105f409afc52/code/game/gamemodes/malfunction/Malf_Modules.dm#L475-L476
