### ISSUE TITLE
Fungus doesn't exist, making Spaceacillin production impossible

### ISSUE THREAD

**Issue by spoonitate** [OracleStation/OracleStation#879]
**Problem Description**: Title. Fungal clusters don't spawn on station; every recipe that requires spaceacillin is now impossible to create.

**Why is this bad/What are the consequences**: Due to to the limited initial supply of spaceacillin, large-scale biohazard containment procedures are difficult. Oculine and Rezadone, two chems useful in cryomixes, are impossible to manufacture as well. Any viral biohazard events that require spaceacillin as a cure are now incredibly lethal.

From what I can see, the solution is to either rework the entire medical system and adjust everything that requires spaceacillin... Or, you know, just find a way to spawn fungus on-station.

**Comment by Ziiro** [comment]
One of the ideas I had to fix this was having Lavaland mushrooms produce it when blended. Or changing the recipe to involve something that those already produce when ground up.

**Comment by spoonitate** [comment]
This would add some more functionality to miners, but considering they have to worry about getting materials for science and slaying monsters they might not be as receptive to having something waste precious inventory space for relatively little gain.

Alternatively, mushrooms grown in hydroponics could produce fungus alongside whatever else they have.

**Comment by AndrewMontagne** [comment]
Was fixed. Magic mushrooms take the place of fungus.
