### ISSUE TITLE
LOOC broke after flattest's PR

### ISSUE THREAD

**Issue by AffectedArc07** [OracleStation/OracleStation#880]
Issue reported from Round ID: 2144 (Oracle Station | Medium RP)

Honestly flattest, you never test anything
![image](https://user-images.githubusercontent.com/25063394/39592678-6bef9432-4eff-11e8-8bee-2c4d79f0b4c3.png)
This happens when you are IN your body, ALIVE

**Comment by FlattestGuitar** [comment]
kek
