### ISSUE TITLE
Synthanol not working

### ISSUE THREAD

**Issue by tomdroid123** [OracleStation/OracleStation#890]
Issue reported from Round ID: 2181 (Oracle Station | Medium RP)

I combined stable plasma, space lube, and welding fuel. According to the WIKI, this makes Synthanol. Nothing happened.I had 20 units of space lube, 20 units of plasma, and 20 units of fuel.

**Comment by Citinited** [comment]
FYI, that recipe calls for ground-up plasma sheets, not stable plasma from the dispenser.
