### ISSUE TITLE
Oxygen either ran out, or broke.

### ISSUE THREAD

**Issue by Ralta** [OracleStation/OracleStation#891]
**Round ID:** 2185

![Where did all the pressure go.png](https://i.imgur.com/lbqX0xa.png)

No idea what happened here, but right at round end, an atmos tech (@Roleplay Rascal) informed me of the pressure being basically nil for O2. No idea how this happened, since there should be nigh on infinite gas, right? 

Couldn't see anything obviously causing the problem, doing the obvious stuff like _turning it off and on again_ didn't help.

**Comment by Kokojos** [comment]
Pretty sure an Admin ran my ''Clean air'' command next to it, thus killing the tile.

**Comment by AndrewMontagne** [comment]
This hasn't re-occured. Closing.
