### ISSUE TITLE
roundstart wikilinks are broke. #2411

### ISSUE THREAD

**Issue by miniusAreas** [OracleStation/OracleStation#916]
Links to the wiki regarding a few jobs are broken. Unknown what ones, but be safe to try them all.

**Comment by Ziiro** [comment]
Gonna need some more data. What does the URL on the job start say, and where does it go in the browser?

This was added via https://github.com/OracleStation/OracleStation/pull/774 and should redirect properly, but it clearly isn't. 🤔
