### ISSUE TITLE
[Metastation] Bar Monkey and facehugger

### ISSUE THREAD

**Issue by Quantum-M** [OracleStation/OracleStation#921]
Round ID: 2429

The monkey that spawns in the bar in metastation, which can spawn with different hats and masks, has a chance to spawn a **_real_** facehugger mask, making it that there is a chance for there to be a free xenomorph near to round start.

**Comment by Cactus2388** [comment]
feature

**Comment by AdamElTablawy** [comment]
was actually ruled as a feature on /tg/

**Comment by Quantum-M** [comment]
Good grief, that means metastation has _**TWO**_ chances of spawning a xenomorph of some sort then at round start, that including the xenobiology

**Comment by AdamElTablawy** [comment]
yes

**Comment by SamHPurp** [comment]
Feature, if you want it gone, it'd need a PR, not an issue.
