### ISSUE TITLE
Frosty Lava

### ISSUE THREAD

**Issue by SamHPurp** [OracleStation/OracleStation#98]
![image](https://user-images.githubusercontent.com/7415122/31038829-c9f93c92-a570-11e7-9315-056860d094c5.png)

@AndrewMontagne

**Comment by LuamTheElf** [comment]
It's so hot it's cold

**Comment by ike709** [comment]
Wouldn't adding a z level check to the frost code more or less fix this, though?

**Comment by SamHPurp** [comment]
@ike709 100%
