### ISSUE TITLE
Lavaland Ashwalkers sprite: Curretly slightly broken.

### ISSUE THREAD

**Issue by EldritchSigma** [OracleStation/OracleStation#99]
Looks like the ashwalkers are missing the middle part of their body. Looks very funky. 

How to reproduce: Pick Ashwalker, look at the funky middle bodypart. Looks like they are missing shit.

Woops literally got a PR as I was typing this. Disregard.

**Comment by FlattestGuitar** [comment]
ONE STEP AHEAD

https://github.com/OracleStation/OracleStation/pull/97
