### ISSUE TITLE
ERT encryption keys prevent ERT from talking to station channels

### ISSUE THREAD

**Issue by Captaincardgage** [OracleStation/OracleStation#993]
Round: N/A
Issue: ERT encryption keys cannot be used to communicate with the station.

ERT radios work fine until they get on station where the Central Command Encryption key prevents anyone with it in their radio from talking to anyone not with CC channels or the key itself. If its removed from the headset then it works normally and the crew can actually talk to them or hear them over the radio. 

How to recreate: Have any radio headset (recommend using the CC ones) have the Central command key inside it and try to talk to the crew over the radio. It should send any message to the crew but they wont hear it, even if you talk over common radio.

**Comment by tjg1** [comment]
/tg/ fixed this as part of a large radio system refactor: https://github.com/tgstation/tgstation/pull/33647
